name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Install dependencies
      run: |
        gem install bundler -v 2.3.26
        bundle install

    - name: Build the site to docs/
      run: bundle exec jekyll build --destination docs

    - name: Commit built site to docs/
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add docs
        git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
        git push
